# Generated by Django 5.2.8 on 2025-11-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueGasolina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GAS_COMUM', 'Gasolina Comum'), ('GAS_ADITIVADA', 'Gasolina Aditivada'), ('DIESEL_COMUM', 'Diesel Comum'), ('DIESEL_S10', 'Diesel S-10'), ('ETANOL', 'Etanol')], max_length=20, unique=True, verbose_name='Tipo de Combustível')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Estoque (Litros)')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Estoque de Combustível',
                'verbose_name_plural': 'Estoque de Combustíveis',
            },
        ),
    ]
