# Generated by Django 5.2.8 on 2025-11-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True, verbose_name='Data da Compra')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade (L)')),
                ('preco_compra_litro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Compra por Litro (R$)')),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Pago (R$)')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.estoquegasolina', verbose_name='Combustível Comprado')),
            ],
            options={
                'verbose_name': 'Registro de Compra',
                'verbose_name_plural': 'Registros de Compras',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='RegistroVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade (L)')),
                ('preco_venda_litro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda por Litro (R$)')),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Recebido (R$)')),
                ('combustivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.estoquegasolina', verbose_name='Combustível Vendido')),
            ],
            options={
                'verbose_name': 'Registro de Venda',
                'verbose_name_plural': 'Registros de Vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
