# Generated by Django 5.2.8 on 2025-11-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_registrocompra_registrovenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquegasolina',
            name='preco_atual_litro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Atual por Litro (R$)'),
        ),
    ]
