# Generated by Django 5.2.8 on 2025-11-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_estoquegasolina_preco_atual_litro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço por Unidade (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='RegistroServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Registro de Serviço',
                'verbose_name_plural': 'Registros de Serviços',
                'ordering': ['-data'],
            },
        ),
    ]
