# Generated by Django 5.2.8 on 2025-12-13 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=18, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id_number', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('full_name', models.CharField(max_length=255)),
                ('hire_date', models.DateField(verbose_name='Data de Contratação')),
                ('job_title', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='É Gerente')),
            ],
        ),
    ]
