# Generated by Django 5.2.8 on 2025-12-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='employee_id_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='hire_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Contratação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='job_title',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('FRENTISTA', 'Frentista'), ('CAIXA', 'Caixa'), ('MECANICO', 'Mecânico'), ('AUXILIAR', 'Auxiliar de Serviços Gerais')], max_length=20, verbose_name='Cargo'),
        ),
    ]
